Repository SEIIGruppe2/App, pull requests merged in 2024-03, with the labels that each got.

#6 docs: Markdown, Git & Doku
  docs/MarkdownTemplate.md
  docs/README.md
Labels: documentation, question

#8 docs: Added documentation for TCP connection and Observable usage
  README.md
Labels: documentation

#10 docs: MVC Research
  docs/mvc.md
Labels: question

#11 3 setup for server communication
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/munchkin/MainActivity.java
  app/src/main/java/com/example/munchkin/networking/WebSocketClient.java
  app/src/main/java/com/example/munchkin/networking/WebSocketMessageHandler.java
  app/src/main/res/layout/activity_main.xml
Labels: enhancement
