Repository SEIIGruppe2/App, pull requests merged in 2024-06, with the labels that each got.

#79 Feature Branch: Game Termination, Screens, Lobby Flexibility, and Cheating Features
  .idea/deploymentTargetDropDown.xml
  .idea/encodings.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/munchkin/DrawableUtils/CardUtils.java
  app/src/main/java/com/example/munchkin/MessageFormat/MessageFormatter.java
  app/src/main/java/com/example/munchkin/Options.java
  app/src/main/java/com/example/munchkin/activity/AllLoseActivity.java
  app/src/main/java/com/example/munchkin/activity/CarddeckActivity.java
  app/src/main/java/com/example/munchkin/activity/ConnectToServerActivity.java
  app/src/main/java/com/example/munchkin/activity/GameRules.java
  app/src/main/java/com/example/munchkin/activity/LoadingscreenActivity.java
  app/src/main/java/com/example/munchkin/activity/LobbyActivity.java
  app/src/main/java/com/example/munchkin/activity/LoseActivity.java
  app/src/main/java/com/example/munchkin/activity/MainActivity.java
  app/src/main/java/com/example/munchkin/activity/MainGameActivity.java
  app/src/main/java/com/example/munchkin/activity/WinActivity.java
  app/src/main/java/com/example/munchkin/controller/CardDeckController.java
  app/src/main/java/com/example/munchkin/controller/ConnectToServerController.java
  app/src/main/java/com/example/munchkin/controller/GameController.java
  app/src/main/java/com/example/munchkin/controller/LoadingController.java
  app/src/main/java/com/example/munchkin/controller/LobbyController.java
  app/src/main/java/com/example/munchkin/controller/SpawnMonsterController.java
  app/src/main/java/com/example/munchkin/networking/WebSocketClient.java
  app/src/main/java/com/example/munchkin/view/CarddeckView.java
  app/src/main/java/com/example/munchkin/view/ConnectToServerView.java
  app/src/main/java/com/example/munchkin/view/MainGameView.java
  app/src/main/java/com/example/munchkin/view/MainView.java
  app/src/main/java/com/example/munchkin/view/animations/ButtonRotateView.java
  app/src/main/res/drawable/logo.jpg
  app/src/main/res/drawable/lose.png
  app/src/main/res/drawable/win_img.png
  app/src/main/res/layout/activity_carddeck.xml
  app/src/main/res/layout/activity_connect_to_server.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_main_game.xml
  app/src/main/res/layout/all_lose_screen.xml
  app/src/main/res/layout/game_rules.xml
  app/src/main/res/layout/lose_screen.xml
  app/src/main/res/layout/options.xml
  app/src/main/res/layout/popup_accuse_cheater.xml
  app/src/main/res/layout/win_screen.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/raw/munchkinpanic.mp3
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/example/munchkin/DrawableUtils/CardUtilsTest.java
  app/src/test/java/com/example/munchkin/MessageFormat/MessageFormatterTest.java
  gradle/libs.versions.toml
Labels: bug, documentation, enhancement, refactoring

#81 80 resolve code smells
  app/src/androidTest/java/com/example/munchkin/ExampleInstrumentedTest.java
  app/src/main/java/com/example/munchkin/DTO/ActionCardDTO.java
  app/src/main/java/com/example/munchkin/Options.java
  app/src/main/java/com/example/munchkin/activity/CarddeckActivity.java
  app/src/main/java/com/example/munchkin/activity/ConnectToServerActivity.java
  app/src/main/java/com/example/munchkin/activity/LoadingscreenActivity.java
  app/src/main/java/com/example/munchkin/activity/LobbyActivity.java
  app/src/main/java/com/example/munchkin/activity/MainActivity.java
  app/src/main/java/com/example/munchkin/activity/MainGameActivity.java
  app/src/main/java/com/example/munchkin/controller/CardDeckController.java
  app/src/main/java/com/example/munchkin/controller/ConnectToServerController.java
  app/src/main/java/com/example/munchkin/controller/DrawCardController.java
  app/src/main/java/com/example/munchkin/controller/GameController.java
  app/src/main/java/com/example/munchkin/controller/LoadingController.java
  app/src/main/java/com/example/munchkin/controller/LobbyController.java
  app/src/main/java/com/example/munchkin/controller/SpawnMonsterController.java
  app/src/main/java/com/example/munchkin/drawableutils/CardUtils.java
  app/src/main/java/com/example/munchkin/dto/ActionCardDTO.java
  app/src/main/java/com/example/munchkin/dto/EntityDTO.java
  app/src/main/java/com/example/munchkin/dto/MonsterDTO.java
  app/src/main/java/com/example/munchkin/dto/TowerDTO.java
  app/src/main/java/com/example/munchkin/game/GameRound.java
  app/src/main/java/com/example/munchkin/messageformat/MessageFormatter.java
  app/src/main/java/com/example/munchkin/messageformat/MessageRouter.java
  app/src/main/java/com/example/munchkin/model/WebSocketClientModel.java
  app/src/main/java/com/example/munchkin/player/Player.java
  app/src/main/java/com/example/munchkin/player/PlayerHand.java
  app/src/main/java/com/example/munchkin/view/CarddeckView.java
  app/src/main/java/com/example/munchkin/view/MainGameView.java
  app/src/main/java/com/example/munchkin/view/MainView.java
  app/src/main/java/com/example/munchkin/view/MonsterManager.java
  app/src/main/java/com/example/munchkin/view/animations/ButtonRotateView.java
  app/src/main/java/com/example/munchkin/view/animations/ZoomDetectorView.java
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/example/munchkin/drawableutils/CardUtilsTest.java
  app/src/test/java/com/example/munchkin/dto/ActionCardDTOTest.java
  app/src/test/java/com/example/munchkin/dto/EntityDTOTest.java
  app/src/test/java/com/example/munchkin/dto/MonsterDTOTest.java
  app/src/test/java/com/example/munchkin/dto/TowerDTOTest.java
  app/src/test/java/com/example/munchkin/game/GameRoundTest.java
  app/src/test/java/com/example/munchkin/messageformat/MessageFormatterTest.java
  app/src/test/java/com/example/munchkin/messageformat/MessageRouterTest.java
  app/src/test/java/com/example/munchkin/player/PlayerHandTest.java
  app/src/test/java/com/example/munchkin/player/PlayerTest.java
Labels: refactoring

#84 82 refactoring and enhancing maintainability
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/munchkin/activity/CardDeckActivity.java
  app/src/main/java/com/example/munchkin/activity/CarddeckActivity.java
  app/src/main/java/com/example/munchkin/activity/ConnectToServerActivity.java
  app/src/main/java/com/example/munchkin/activity/LoadingScreenActivity.java
  app/src/main/java/com/example/munchkin/activity/MainGameActivity.java
  app/src/main/java/com/example/munchkin/controller/CardDeckController.java
  app/src/main/java/com/example/munchkin/controller/DrawCardController.java
  app/src/main/java/com/example/munchkin/controller/GameController.java
  app/src/main/java/com/example/munchkin/controller/LoadingController.java
  app/src/main/java/com/example/munchkin/controller/SpawnMonsterController.java
  app/src/main/java/com/example/munchkin/interfaces/GameEventHandler.java
  app/src/main/java/com/example/munchkin/networking/WebSocketClient.java
  app/src/main/java/com/example/munchkin/view/CardDeckView.java
  app/src/main/java/com/example/munchkin/view/CarddeckView.java
  app/src/main/java/com/example/munchkin/view/LobbyView.java
  app/src/main/java/com/example/munchkin/view/MainGameView.java
  app/src/main/java/com/example/munchkin/view/MainView.java
  app/src/main/res/drawable/board.png
  app/src/main/res/layout/activity_carddeck.xml
  app/src/main/res/layout/activity_loadingscreen.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/example/munchkin/drawableutils/CardUtilsTest.java
  app/src/test/java/com/example/munchkin/dto/ActionCardDTOTest.java
  app/src/test/java/com/example/munchkin/dto/EntityDTOTest.java
  app/src/test/java/com/example/munchkin/dto/MonsterDTOTest.java
  app/src/test/java/com/example/munchkin/dto/TowerDTOTest.java
  app/src/test/java/com/example/munchkin/game/AppStateTest.java
  app/src/test/java/com/example/munchkin/messageformat/MessageFormatterTest.java
  app/src/test/java/com/example/munchkin/messageformat/MessageRouterTest.java
  app/src/test/java/com/example/munchkin/model/DiceRollModelTest.java
  app/src/test/java/com/example/munchkin/player/PlayerHandTest.java
  app/src/test/java/com/example/munchkin/player/PlayerTest.java
Labels: enhancement, refactoring

#85 82 refactoring and enhancing maintainability
  app/src/main/java/com/example/munchkin/activity/CardDeckActivity.java
  app/src/main/java/com/example/munchkin/activity/MainGameActivity.java
  app/src/main/java/com/example/munchkin/controller/CardDeckController.java
  app/src/main/java/com/example/munchkin/controller/GameController.java
  app/src/main/java/com/example/munchkin/controller/LobbyController.java
  app/src/main/java/com/example/munchkin/view/LobbyView.java
  app/src/main/java/com/example/munchkin/view/MainGameView.java
Labels: refactoring

#87 removed code smells
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/munchkin/activity/MainActivity.java
  app/src/main/java/com/example/munchkin/controller/LobbyController.java
  app/src/main/java/com/example/munchkin/view/MainView.java
Labels: refactoring
