Repository SEIIGruppe2/App, pull requests merged in 2024-05, with the labels that each got.

#58 38 monster designen
  app/src/main/java/com/example/munchkin/activity/MainGameActivity.java
  app/src/main/java/com/example/munchkin/view/DiceRollView.java
  app/src/main/java/com/example/munchkin/view/MainGameView.java
  app/src/main/java/com/example/munchkin/view/animations/ButtonRotateView.java
  app/src/main/java/com/example/munchkin/view/animations/ShakeDetectorView.java
  app/src/main/java/com/example/munchkin/view/animations/ZoomDetectorView.java
  app/src/main/res/drawable/monster_bullrog.png
  app/src/main/res/drawable/monster_slime.png
  app/src/main/res/drawable/monster_sphinx.png
  app/src/test/java/com/example/munchkin/Player/PlayerTest.java
  app/src/test/java/com/example/munchkin/game/GameRoundTest.java
Labels: enhancement

#60 51 erweiterung und verbesserung der tests
  app/src/main/res/layout/activity_dice_roll.xml
  app/src/test/java/com/example/munchkin/DTO/ActionCardDTOTest.java
  app/src/test/java/com/example/munchkin/DTO/EntityDTOTest.java
  app/src/test/java/com/example/munchkin/DTO/MonsterDTOTest.java
  app/src/test/java/com/example/munchkin/DTO/TowerDTOTest.java
  app/src/test/java/com/example/munchkin/DrawableUtils/CardUtilsTest.java
  app/src/test/java/com/example/munchkin/ExampleUnitTest.java
  app/src/test/java/com/example/munchkin/MessageFormat/MessageFormatterTest.java
  app/src/test/java/com/example/munchkin/MessageFormat/MessageRouterTest.java
  app/src/test/java/com/example/munchkin/Player/PlayerHandTest.java
  app/src/test/java/com/example/munchkin/model/DiceRollModelTest.java
Labels: enhancement, testing

#66 59 monsterattack
  app/src/main/java/com/example/munchkin/DTO/TowerDTO.java
  app/src/main/java/com/example/munchkin/MessageFormat/MessageFormatter.java
  app/src/main/java/com/example/munchkin/controller/GameController.java
  app/src/main/java/com/example/munchkin/controller/SpawnMonsterController.java
  app/src/main/java/com/example/munchkin/view/MainGameView.java
  app/src/main/java/com/example/munchkin/view/MonsterManager.java
  app/src/main/java/com/example/munchkin/view/animations/ButtonRotateView.java
  app/src/main/res/drawable/tower.png
  app/src/main/res/layout/activity_main_game.xml
  app/src/test/java/com/example/munchkin/DTO/TowerDTOTest.java
  app/src/test/java/com/example/munchkin/MessageFormat/MessageFormatterTest.java
Labels: enhancement, testing, refactoring

#72 65 code refactoring
  app/src/main/java/com/example/munchkin/MessageFormat/MessageFormatter.java
  app/src/main/java/com/example/munchkin/MessageFormat/MessageRouter.java
  app/src/main/java/com/example/munchkin/activity/CarddeckActivity.java
  app/src/main/java/com/example/munchkin/activity/LoadingscreenActivity.java
  app/src/main/java/com/example/munchkin/activity/LobbyActivity.java
  app/src/main/java/com/example/munchkin/activity/MainActivity.java
  app/src/main/java/com/example/munchkin/activity/MainGameActivity.java
  app/src/main/java/com/example/munchkin/activity/TradeCardsActivity.java
  app/src/main/java/com/example/munchkin/controller/BaseController.java
  app/src/main/java/com/example/munchkin/controller/CardDeckController.java
  app/src/main/java/com/example/munchkin/controller/ConnectToServerController.java
  app/src/main/java/com/example/munchkin/controller/DrawCardController.java
  app/src/main/java/com/example/munchkin/controller/GameController.java
  app/src/main/java/com/example/munchkin/controller/LoadingController.java
  app/src/main/java/com/example/munchkin/controller/LobbyController.java
  app/src/main/java/com/example/munchkin/controller/SpawnMonsterController.java
  app/src/main/java/com/example/munchkin/game/GameRound.java
  app/src/main/java/com/example/munchkin/model/DiceRollModel.java
  app/src/main/java/com/example/munchkin/model/WebSocketClientModel.java
  app/src/main/java/com/example/munchkin/networking/WebSocketClient.java
  app/src/main/java/com/example/munchkin/view/CarddeckView.java
  app/src/main/java/com/example/munchkin/view/ConnectToServerView.java
  app/src/main/java/com/example/munchkin/view/DiceRollView.java
  app/src/main/java/com/example/munchkin/view/LobbyView.java
  app/src/main/java/com/example/munchkin/view/MainGameView.java
  app/src/main/java/com/example/munchkin/view/MainView.java
  app/src/main/java/com/example/munchkin/view/TradeCardsView.java
  app/src/main/java/com/example/munchkin/view/animations/ButtonRotateView.java
  app/src/test/java/com/example/munchkin/DrawableUtils/CardUtilsTest.java
  app/src/test/java/com/example/munchkin/MessageFormat/MessageFormatterTest.java
  app/src/test/java/com/example/munchkin/game/GameRoundTest.java
Labels: enhancement, refactoring
